name: Reporting

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Test report
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: 'Test report summary'
        path: 'test-results-*.json'
        reporter: mocha-json
        list-suites: all
        list-tests: failed
